# Generated by Django 4.2.30 on 2026-05-02 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_demographic', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinical_queries',
            },
        ),
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clinicalquery')),
            ],
            options={
                'db_table': 'query_responses',
            },
        ),
        migrations.CreateModel(
            name='BiasAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clinicalquery')),
            ],
            options={
                'db_table': 'bias_audit_logs',
            },
        ),
    ]
